# Generated by Django 3.1 on 2020-08-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_db',
            name='title',
            field=models.TextField(),
        ),
    ]
